server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ead_authuser
    username: decoder
    password: decoder
  jpa:
    hibernate:
      ddl-auto: update
#      jdbc:
#        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: always
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO