version: '3.8'

services:

  decoder-db:
    container_name: decoderpostgres
    image: postgres:alpine
    restart: always
    volumes:
      - ./docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql
    environment:
      POSTGRES_MULTIPLE_DATABASES: ead_authuser_v2, ead_course_v2
      POSTGRES_USER: decoder
      POSTGRES_PASSWORD: decoder
    ports:
      - "5434:5432"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
