version: '3.8'

services:

  db:
    container_name: decoder
    image: postgres:alpine
    restart: always
    volumes:
      - ./docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-decoder-init.sql
    environment:
      POSTGRES_MULTIPLE_DATABASES: ead-authuser, ead-course
      POSTGRES_USER: decoder
      POSTGRES_PASSWORD: decoder
    ports:
      - "5434:5432"
    networks:
      - postgres-compose-network

#  pgadmin:
#    container_name: pgadmin4
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "15432:80"
#    networks:
#      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
